### ISSUE TITLE
Lottery event "fan" option doesnt work

### ISSUE THREAD

**Issue by LetterN** [daredloco/Random-Events-Mod-for-Software-Inc#1]
## Describe the bug
Title. It's due to how i do not have any products released causing nothing to happen

## To Reproduce
1. Start game with no products released
2. Wait (or manually trigger) "Win the lottery" event
3. Click "I want to donate it!"
4. No fans added

## Expected behavior
Fans added

A way to probably make this not happen is have the event check if you even have stuff released/has fans on any category

**Comment by daredloco** [comment]
Thanks for the info. It was an oversight by my side, as you need to have at least one product released to get fans.
I'll accept your pull request, as it could be a possible fix for this specific problem.

Thanks!

Edit: An update is on Steam already
